services:
  api:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"   # FastAPI
    env_file:
      - .env
    depends_on:
      - chroma
    volumes:
      - ./data:/app/data
      - ./src:/app/src

  streamlit:
    build: .
    command: streamlit run ui/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"   # Streamlit
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      - ./data:/app/data
      - ./ui:/app/ui
      - ./src:/app/src

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma_data

volumes:
  chroma_data:
